CREATE TABLE hotel_bookings (
    booking_id VARCHAR(20) PRIMARY KEY,
    hotel VARCHAR(50),
    is_canceled TINYINT,
    lead_time INT,
    arrival_date_year INT,
    arrival_date_month VARCHAR(20),
    arrival_date_week_number INT,
    stays_in_weekend_nights INT,
    stays_in_week_nights INT,
    adults INT,
    children INT,
    babies INT,
    meal VARCHAR(30),
    country VARCHAR(10),
    market_segment VARCHAR(50),
    distribution_channel VARCHAR(50),
    customer_type VARCHAR(50),
    adr DECIMAL(10,2),
    total_of_special_requests INT,
    reservation_status VARCHAR(30)
);
